apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer
  annotations:
    fluxcd.io/automated: "false"
  namespace: manufacturer-ns
spec:
  releaseName: manufacturer
  chart:
    path: platforms/r3-corda/charts/node
    git: ssh://git@github.com/cythe14/blockchain-automation-framework.git
    ref: gke
  values:
    nodeName: manufacturer
    replicas: 1
    metadata:
      namespace: manufacturer-ns
    image:
      containerName: index.docker.io/cythe14/corda:4.6-linuxkit
      initContainerName: index.docker.io/cythe14/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 35.202.201.186
      networkmapCertAlias: 34.123.214.236
    nodeConf:
      p2p:
        url: manufacturer.manufacturer-ns
        port: 10002
      ambassadorAddress: manufacturer.develop.local.com:15020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: manufacturerdb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://manufacturerdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://34.123.214.236:30040
      doormanURL: http://35.202.201.186:30030
      compatibilityZoneURL:
      jarVersion: 4.6
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: manufactureroperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: manufacturer-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: gcpstorageclass

    service:
      name: manufacturer
      type: NodePort
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://34.123.214.236:32047
      role: vault-role
      authpath: cordamanufacturer
      serviceaccountname: vault-auth
      dbsecretprefix: manufacturer/credentials/database
      rpcusersecretprefix: manufacturer/credentials/rpcusers
      tokensecretprefix: manufacturer/credentials/vaultroottoken
      keystoresecretprefix: manufacturer/credentials/keystore
      certsecretprefix: manufacturer/certs
      networkmapsecretprefix: manufacturer/credentials/networkmappassword
      cordappsreposecretprefix: manufacturer/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: manufacturer
      external_url_suffix: develop.local.com
      p2p_ambassador: 15020
      
