apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary-initial-registration
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ns
spec:
  releaseName: notary-initial-registration
  chart:
    path: platforms/r3-corda/charts/notary-initial-registration
    git: ssh://git@github.com/cythe14/blockchain-automation-framework.git
    ref: gke
  values:
    nodeName: notary
    replicas: 1
    metadata:
      namespace: supplychain-ns  
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.4-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 35.202.201.186
      networkmapCertAlias: 34.123.214.236
    nodeConf:
      p2p:
        url: notary.supplychain-ns
        port: 10006
      ambassadorAddress: notary.develop.local.com:15010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10007"
        adminAddress: "0.0.0.0:10008"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: false
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: notarydb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notarydb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://34.123.214.236:30040
      doormanURL: http://35.202.201.186:30030
      compatibilityZoneURL:
      jarVersion: 4.4
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notaryoperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10006
        targetPort: 10006
      rpc:
        port: 10007
      rpcadmin:
        port: 10008

    vault:
      address: http://34.123.214.236:32047
      role: vault-role
      authpath: cordanotary
      serviceaccountname: vault-auth
      dbsecretprefix: notary/credentials/database
      rpcusersecretprefix: notary/credentials/rpcusers
      tokensecretprefix: notary/credentials/vaultroottoken
      keystoresecretprefix: notary/credentials/keystore
      certsecretprefix: notary/certs
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
