apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ns
spec:
  releaseName: notary
  chart:
    path: platforms/r3-corda/charts/notary
    git: ssh://git@github.com/cythe14/blockchain-automation-framework.git
    ref: local
  values:
    nodeName: notary
    replicas: 1
    metadata:
      namespace: supplychain-ns
    image:
      containerName: index.docker.io/cythe14/corda:4.6-linuxkit
      initContainerName: index.docker.io/cythe14/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 10.0.2.15
      networkmapCertAlias: 10.0.2.15
    nodeConf:
      p2p:
        url: notary.supplychain-ns
        port: 10006
      ambassadorAddress: notary.develop.local.com:15010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10007"
        adminAddress: "0.0.0.0:10008"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: false
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: notarydb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notarydb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://10.0.2.15:30040
      doormanURL: http://10.0.2.15:30030
      compatibilityZoneURL:
      jarVersion: 4.6
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notaryoperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: notary-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: microk8sstorageclass

    service:
      name: notary
      type: ClusterIP
      p2p:
        port: 10006
        targetPort: 10006
      rpc:
        port: 10007
        targetPort: 10007 
      rpcadmin:
        port: 10008
        targetPort: 10008
         
    deployment:
      annotations: {}
    vault:
      address: http://10.1.233.8:8200
      role: vault-role
      authpath: cordanotary
      serviceaccountname: vault-auth
      dbsecretprefix: notary/credentials/database
      rpcusersecretprefix: notary/credentials/rpcusers
      tokensecretprefix: notary/credentials/vaultroottoken
      keystoresecretprefix: notary/credentials/keystore
      certsecretprefix: notary/certs
      networkmapsecretprefix: notary/credentials/networkmappassword
      cordappsreposecretprefix: notary/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: notary
      external_url_suffix: develop.local.com
      p2p_ambassador: 15010
      
