kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: {​​{​​ component_name }​​}​​
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
    encrypted: "true"